coverage_server:
  ros__parameters:
    use_sim_time: True
    default_headland_width: 0.25
    robot_width: 0.7
    operation_width: 0.7
    min_turning_radius: 0.35
    linear_curv_change: 200.0
    coordinates_in_cartesian_frame: true
    default_allow_overlap: false
    default_swath_angle_type: "SET_ANGLE"
    default_swath_angle: 0.0 # We know its aligned for the demo

row_coverage_server:
  ros__parameters:
    use_sim_time: True
    robot_width: 0.7
    operation_width: 0.7
    min_turning_radius: 0.35
    linear_curv_change: 200.0
    coordinates_in_cartesian_frame: true
    default_swath_type: "CENTER"
    default_offset: 0.0

bt_navigator:
  ros__parameters:
    use_sim_time: True
    global_frame: map
    robot_base_frame: base_link
    odom_topic: odom
    bt_loop_duration: 10
    default_server_timeout: 20
    # 'default_coverage_bt_xml' uses defaults:
    # opennav_coverage_bt/behavior_tree/navigate_w_basic_complete_coverage.xml
    navigators: ['navigate_complete_coverage']
    navigate_complete_coverage:
      plugin: "opennav_coverage_navigator/CoverageNavigator"
    error_code_names: ["compute_path_error_code", "follow_path_error_code", "compute_coverage_error_code"]
    plugin_lib_names:
      - nav2_follow_path_action_bt_node
      - nav2_rate_controller_bt_node
      - nav2_recovery_node_bt_node
      - nav2_pipeline_sequence_bt_node
      - nav2_round_robin_node_bt_node
      - opennav_compute_complete_coverage_action_bt_node
      - opennav_cancel_complete_coverage_action_bt_node

bt_navigator_navigate_complete_coverage_rclcpp_node:
  ros__parameters:
    use_sim_time: True
